---
- name: Make ss14 config
  ansible.builtin.template:
    src: templates/server_config.toml
    dest: "{{ deploy_helper.shared_path }}/server"
    owner: "{{ ss14_unix_user }}"
    group: "{{ ss14_unix_group }}"
    mode: "0744"
  notify:
    - Start_ss14
    - Restart_ss14
