---
- name: Make temp apt key dir
  ansible.builtin.file:
    state: directory
    path: "/tmp/apt_key"
    owner: root
    group: root
    mode: "0700"

- name: Apt key
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb"
    dest: "/tmp/apt_key/packages-microsoft-prod.deb"
    owner: root
    group: root
    mode: "0700"
  changed_when: false

- name: Run apt key
  ansible.builtin.command: "dpkg -i packages-microsoft-prod.deb"
  args:
    chdir: "/tmp/apt_key"
  changed_when: false

- name: Install dotnet runtime
  ansible.builtin.apt:
    pkg: "dotnet-runtime-8.0"
    update_cache: true
  notify: Restart_ss14
