---
- name: Template systemd unit
  template:
    src: "templates/ss14.service"
    dest: "/etc/systemd/system/{{ ss14_name }}.service"
    owner: root
    group: root
    mode: 700
  notify:
    - daemon_reload
    - restart_ss14
