---
- name: Template systemd unit
  ansible.builtin.template:
    src: "templates/ss14.service"
    dest: "/etc/systemd/system/{{ ss14_name }}.service"
    owner: root
    group: root
    mode: "0700"
  notify:
    - Daemon_reload
    - Restart_ss14
