---
- name: Daemon_reload
  ansible.builtin.service:
    name: "{{ ss14_name }}.service"
    daemon_reload: true

- name: Restart_ss14
  ansible.builtin.service:
    name: "{{ ss14_name }}.service"
    state: restarted

- name: Start_ss14
  ansible.builtin.service:
    name: "{{ ss14_name }}.service"
    state: started
    enabled: true
