---
- name: daemon_reload
  service:
    daemon_reload: true

- name: restart_ss14
  service:
    name: "{{ ss14_name }}.service"
    state: restarted

- name: start_ss14
  service:
    name: "{{ ss14_name }}.service"
    state: started
    enabled: true
