#
# {{ ansible_managed }}
#

[net]
tickrate = {{ ss14_net_tickrate }}
port = {{ ss14_net_port }}

[game]
hostname = "{{ ss14_game_hostname }}"
desc = "{{ ss14_game_description }}"
lobbyenabled = {{ ss14_game_lobby_enabled | bool }}
maxplayers = {{ ss14_game_maxplayers }}

[auth]
mode = {{ ss14_auth_mode }}

[log]
enabled = {{ ss14_log_enabled | bool }}
path = "{{ ss14_log_path }}"

[adminlogs]
enabled = {{ ss14_admin_log_enabled | bool }}

[loki]
enabled = {{ ss14_loki_enabled | bool }}
{% if ss14_loki_name is defined -%}name = "{{ ss14_loki_name }}"{% endif %}
{% if ss14_loki_address is defined -%}address = "{{ ss14_loki_address }}"{% endif %}
{% if ss14_loki_username is defined -%}username = "{{ ss14_loki_username }}"{% endif %}
{% if ss14_loki_password is defined -%}password = "{{ ss14_loki_password }}"{% endif %}
